### ISSUE TITLE
Homebridge plugin

### ISSUE THREAD

**Issue by philhar88** [NovaGL/diy-melview#3]
Hello,

Would you be interested in creating a home bridge plugin for this API?

I think it would work best if it used the following structure from the LC response XML?

### Service.Information
Generic information about the accessory (required)
### Service.Thermostat
The basic thermostat service that replaces HeaterCoolerService
#### Characteristic.CurrentHeatingCoolingState
standby : 0|1, setmode : %
#### Characteristic.TargetHeatingCoolingState
standby : 0|1, setmode : %
#### Characteristic.CurrentTemperature
roomtemp : "%"
#### Characteristic.TargetTemperature
settemp : "%"
#### Characteristic.TemperatureDisplayUnits
(hardcode to c)

### Service.Fanv2
The global fan service of the unit
#### Characteristic.Active
standby : 0|1
#### Characteristic.RotationSpeed
setfan : 0...5

### Service.Switch[0...8]
This would control each zone
#### Characteristic.On
zones[0...8].zoneid : 0|1
#### Characteristic.Name
zones[0...8].name : "zone name"

**Comment by NovaGL** [comment]
Thanks for the idea, I'm happy to help you make one but the purpose of this repo is informational only.

I'm actually doing what you want using another plugin. Rather than create a whole new homebridge plugin. I use Homekit2MQTT, it basically uses the stored information in MQTT and passes the command that way. Let me know if you need more information

The problem around a Homebridge plugin (for me) is the cookie and how to make it dynamic.

**Comment by philhar88** [comment]
Thanks for the quick reply. I believe it should be possible to compare the cookie expiry field before each command is sent and then simply skip getting a new cookie if so. I will investigate writing the plugin
